### ISSUE TITLE
钉钉报警的模板问题

### ISSUE THREAD

**Issue by yuge994** [feiyu563/PrometheusAlert#137]
有两个问题想请教
钉钉的报警模板可以调整字体颜色的吗，像微信那样 <font color=info>
模板里面取持续时间应该怎么取  之前我用dingtalk-webhook是这么写  {{ .EndsAt.Sub .StartsAt }}    不过用prometheusalert好像这么写不生效   尝试这么写{{$v.EndsAt.Sub $v.StartsAt}}   也不生效

**Comment by feiyu563** [comment]
sub应该是自定义的函数，PrometheusAlert没有写这方面的自定义函数所以没法使用

**Comment by feiyu563** [comment]
调整字体颜色可以参考钉钉官方文档中关于钉钉机器人markdown的部分描述，我记得是有关于字体方面调整的，实在不行可以使用HTML语法试试

**Comment by yuge994** [comment]
> sub应该是自定义的函数，PrometheusAlert没有写这方面的自定义函数所以没法使用

是否可以考虑增加一个类似的函数，个人感觉持续时间在报警里面很实用

**Comment by feiyu563** [comment]
这个我考虑下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月23日(周一) 下午5:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] 钉钉报警的模板问题 (#137)




  
sub应该是自定义的函数，PrometheusAlert没有写这方面的自定义函数所以没法使用
  
是否可以考虑增加一个类似的函数，个人感觉持续时间在报警里面很实用
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
