### ISSUE TITLE
华为云短信测试报错

### ISSUE THREAD

**Issue by wyman1217** [feiyu563/PrometheusAlert#143]
测试华为云短信，报错，返回如下。E000000，貌似是格式的问题？但我只在app.conf上配置了相关内容。
{"code":"E000000","description":"System error."}

app.conf的配置如下
open-hwdx=1
#华为云短信接口key
HWY_DX_APP_Key=xxxxxxx
#华为云短信接口Secret
HWY_DX_APP_Secret=xxxxx
#华为云APP接入地址(端口接口地址)
HWY_DX_APP_Url=https://rtcsms.cn-north-1.myhuaweicloud.com:10743
#华为云短信模板ID
HWY_DX_Templateid=xxxxx
#华为云签名名称，必须是已审核通过的，与模板类型一致的签名名称,按照自己的实际签名填写
HWY_DX_Signature=商城测试
#华为云签名通道号
HWY_DX_Sender=xxxxx

**Comment by feiyu563** [comment]
具体的错误原因可以去华为云的官网查下，从报错信息看还是配置的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月16日(周一) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] 华为云短信测试报错 (#143)




 
测试华为云短信，报错，返回如下。E000000，貌似是格式的问题？但我只在app.conf上配置了相关内容。
 {"code":"E000000","description":"System error."}
 
app.conf的配置如下
 open-hwdx=1
 #华为云短信接口key
 HWY_DX_APP_Key=xxxxxxx
 #华为云短信接口Secret
 HWY_DX_APP_Secret=xxxxx
 #华为云APP接入地址(端口接口地址)
 HWY_DX_APP_Url=https://rtcsms.cn-north-1.myhuaweicloud.com:10743
 #华为云短信模板ID
 HWY_DX_Templateid=xxxxx
 #华为云签名名称，必须是已审核通过的，与模板类型一致的签名名称,按照自己的实际签名填写
 HWY_DX_Signature=商城测试
 #华为云签名通道号
 HWY_DX_Sender=xxxxx
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wyman1217** [comment]
跟我的短信模板有关系吗？

模板内容: ${1} 告警设备ip：${2} 时间：${3} 等级：${4} 信息：${5}

**Comment by wyman1217** [comment]
华为云上查到的是：表示系统异常，一般是请求格式异常，短信平台无法解析。
应该是短信的模板和发送的请求格式不一致。

**Comment by feiyu563** [comment]
短信模板只支持一个参数，参考github上的文档就行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月16日(周一) 下午3:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] 华为云短信测试报错 (#143)




 
华为云上查到的是：表示系统异常，一般是请求格式异常，短信平台无法解析。
 应该是短信的模板和发送的请求格式不一致。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
