### ISSUE TITLE
feiyu563/prometheus-alert:lastest镜像的文件换成我自己编译的PrometheusAlert就报错

### ISSUE THREAD

**Issue by wyman1217** [feiyu563/PrometheusAlert#144]
因为我修改了华为短信模板的代码，重新构建了，把我新构建出来的 PrometheusAlert放到正在运行的容器中，替换旧的重新启动容器就报错了，/bin/sh: /app/PrometheusAlert: not found，但是当我把旧的PrometheusAlert放回去，重新启动，又好了。
而我用新的PrometheusAlert 直接执行nohup ./PrometheusAlert &,又是没有问题的，修改的华为短信模板也生效了。

docker cp PrometheusAlert  88f93c099be1:/app/PrometheusAlert
 docker cp PrometheusAlert.20210817.bak 88f93c099be1:/app/PrometheusAlert

docker logs 88f93c099be1 
pass!
table `prometheus_alert_d_b` already exists, skip
table `alert_record` already exists, skip
2021/08/17 06:43:19.285 [I] [proc.go:225]  [main] 当前版本（Version）4.5
2021/08/17 06:43:19.320 [I] [asm_amd64.s:1371]  http server Running on http://0.0.0.0:8080
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
/bin/sh: /app/PrometheusAlert: not found
pass!
table `prometheus_alert_d_b` already exists, skip
table `alert_record` already exists, skip
2021/08/17 06:54:06.012 [I] [proc.go:225]  [main] 当前版本（Version）4.5
2021/08/17 06:54:06.042 [I] [asm_amd64.s:1371]  http server Running on http://0.0.0.0:8080

**Comment by feiyu563** [comment]
执行权限不对



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月17日(周二) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] feiyu563/prometheus-alert:lastest镜像的文件换成我自己编译的PrometheusAlert就报错 (#144)




 
因为我修改了华为短信模板的代码，重新构建了，把我新构建出来的 PrometheusAlert放到正在运行的容器中，替换旧的重新启动容器就报错了，/bin/sh: /app/PrometheusAlert: not found，但是当我把旧的PrometheusAlert放回去，重新启动，又好了。
 而我用新的PrometheusAlert 直接执行nohup ./PrometheusAlert &amp;,又是没有问题的，修改的华为短信模板也生效了。
 
docker cp PrometheusAlert  88f93c099be1:/app/PrometheusAlert
 docker cp PrometheusAlert.20210817.bak 88f93c099be1:/app/PrometheusAlert
 
docker logs 88f93c099be1
 pass!
 table prometheus_alert_d_b already exists, skip
 table alert_record already exists, skip
 2021/08/17 06:43:19.285 [I] [proc.go:225]  [main] 当前版本（Version）4.5
 2021/08/17 06:43:19.320 [I] [asm_amd64.s:1371]  http server Running on http://0.0.0.0:8080
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 /bin/sh: /app/PrometheusAlert: not found
 pass!
 table prometheus_alert_d_b already exists, skip
 table alert_record already exists, skip
 2021/08/17 06:54:06.012 [I] [proc.go:225]  [main] 当前版本（Version）4.5
 2021/08/17 06:54:06.042 [I] [asm_amd64.s:1371]  http server Running on http://0.0.0.0:8080
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wyman1217** [comment]
-rwxr-xr-x 1 root root 25482256 Aug 17 14:24 PrometheusAlert
-rwxr-xr-x 1 root root 25917328 Jul 14 19:02 PrometheusAlert.20210817.bak

这个文件的权限吗？都是755喔

**Comment by feiyu563** [comment]
你可以直接拿现成的dockerfile打包下镜像看看

**Comment by wyman1217** [comment]
用dockerfile构建的就可以
