### ISSUE TITLE
腾讯云短信报错1048

### ISSUE THREAD

**Issue by yangyinghao** [feiyu563/PrometheusAlert#145]
腾讯云短信报错1048，应该是正文中有url导致的，有人知道怎么处理么

**Comment by feiyu563** [comment]
想办法替换掉这些短信不支持的特殊字符



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月23日(周一) 下午2:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] 腾讯云短信报错1048 (#145)




 
腾讯云短信报错1048，应该是正文中有url导致的，有人知道怎么处理么
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
