### ISSUE TITLE
企业微信告警信息markdown文本只支持4096字节，是否考虑对告警文本做切割

### ISSUE THREAD

**Issue by maolchen** [feiyu563/PrometheusAlert#155]
在容器化监控告警的时候，如果出现同一类告警的容器数量过多，通常十个以上甚至七八个的时候，会出现告警文本超出markdown字节数的限制，导致不能收到告警信息。

**Comment by feiyu563** [comment]
这个需要通过优化alertmanager的分组来处理



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月22日(周三) 上午10:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] 企业微信告警信息markdown文本只支持4096字节，是否考虑对告警文本做切割 (#155)




 
在容器化监控告警的时候，如果出现同一类告警的容器数量过多，通常十个以上甚至七八个的时候，会出现告警文本超出markdown字节数的限制，导致不能收到告警信息。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iwz2099** [comment]
`2021/09/27 04:18:42.787 [I] [prometheusalert.go:160]  [1632716322500583981] [weixin] {"errcode":40058,"errmsg":"markdown.content exceed max length 4096. Invalid input invalid Request Parameter, hint: [1632716322_160_81e3fba0e660a9c2c930c940c5181a21], from ip: 47.95.xx.xx, more info at https://open.work.weixin.qq.com/devtool/query?e=40058"}`

遇到同样的问题

**Comment by iwz2099** [comment]
> alertmanager的分组

分组是可以解决，比如同一个分组下有15条报警，每一组报警也会很多，很多人接受的时候大家手机会频繁响；能否给予这15条报警设置分组或者设置一个参数？每次最大报警条数为5条？

**Comment by feiyu563** [comment]
这部分需要配合alertmanager来实现，目前大家都是这么做的

**Comment by lusson-luo** [comment]
> > alertmanager的分组
> 
> 分组是可以解决，比如同一个分组下有15条报警，每一组报警也会很多，很多人接受的时候大家手机会频繁响；能否给予这15条报警设置分组或者设置一个参数？每次最大报警条数为5条？

最后你是怎么解决的呢？
