### ISSUE TITLE
为什么钉钉不同的群，创建自定义机器人，有的群就能触发发送告警，有的群不行呢？

### ISSUE THREAD

**Issue by BadMan008** [feiyu563/PrometheusAlert#156]
自己创建了个钉钉群，测试没有问题，然后创建了一个正式的钉钉群，创建的机器人信息除了名字不一样 其他都一样，把altermanager上webhook地址改成新群的机器人，就是不发送告警。

请问这个有什么限制吗？ 哪里都没变就是改了下钉钉机器人的信息就有的行有的群不行
![image](https://user-images.githubusercontent.com/22131840/134493696-da9a0c1a-3255-454d-b26f-8b9d437cfa11.png)

**Comment by feiyu563** [comment]
改完要重启alertmanager



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月23日(周四) 晚上6:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] 为什么钉钉不同的群，创建自定义机器人，有的群就能触发发送告警，有的群不行呢？ (#156)




 
自己创建了个钉钉群，测试没有问题，然后创建了一个正式的钉钉群，创建的机器人信息除了名字不一样 其他都一样，把altermanager上webhook地址改成新群的机器人，就是不发送告警。
 
请问这个有什么限制吗？ 哪里都没变就是改了下钉钉机器人的信息就有的行有的群不行
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BadMan008** [comment]
alertmanager 配置已经reload啦

**Comment by feiyu563** [comment]
那就看下你的钉钉机器人的安全配置



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月24日(周五) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [feiyu563/PrometheusAlert] 为什么钉钉不同的群，创建自定义机器人，有的群就能触发发送告警，有的群不行呢？ (#156)




 
alertmanager 配置已经reload啦
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
