### ISSUE TITLE
钉钉机器人配置了加签

### ISSUE THREAD

**Issue by bestmem** [feiyu563/PrometheusAlert#157]
您好，请问钉钉机器人配置了加签之后，app.conf内容中如何指定secret？

#是否开启钉钉告警通道,可同时开始多个通道0为关闭,1为开启
open-dingding=1
#默认钉钉机器人地址
ddurl=https://oapi.dingtalk.com/robot/send?access_token=xxxxx
#是否开启 @所有人(0为关闭,1为开启)
dd_isatall=1

**Comment by feiyu563** [comment]
不止加签，目前只支持关键词



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月23日(周四) 晚上7:58
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [feiyu563/PrometheusAlert] 钉钉机器人配置了加签 (#157)




 
d钉钉机器人配置了加签之后，app.conf中如何指定secret？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
